# Generated by Django 5.2.9 on 2025-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benthapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("quote", models.TextField()),
                ("rating", models.PositiveIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
